// Generated by gencpp from file cv_pkg/AddTwoints.msg
// DO NOT EDIT!


#ifndef CV_PKG_MESSAGE_ADDTWOINTS_H
#define CV_PKG_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <cv_pkg/AddTwointsRequest.h>
#include <cv_pkg/AddTwointsResponse.h>


namespace cv_pkg
{

struct AddTwoints
{

typedef AddTwointsRequest Request;
typedef AddTwointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoints
} // namespace cv_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cv_pkg::AddTwoints > {
  static const char* value()
  {
    return "563505b24ec7ec919ab1d0c28096de40";
  }

  static const char* value(const ::cv_pkg::AddTwoints&) { return value(); }
};

template<>
struct DataType< ::cv_pkg::AddTwoints > {
  static const char* value()
  {
    return "cv_pkg/AddTwoints";
  }

  static const char* value(const ::cv_pkg::AddTwoints&) { return value(); }
};


// service_traits::MD5Sum< ::cv_pkg::AddTwointsRequest> should match
// service_traits::MD5Sum< ::cv_pkg::AddTwoints >
template<>
struct MD5Sum< ::cv_pkg::AddTwointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cv_pkg::AddTwoints >::value();
  }
  static const char* value(const ::cv_pkg::AddTwointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cv_pkg::AddTwointsRequest> should match
// service_traits::DataType< ::cv_pkg::AddTwoints >
template<>
struct DataType< ::cv_pkg::AddTwointsRequest>
{
  static const char* value()
  {
    return DataType< ::cv_pkg::AddTwoints >::value();
  }
  static const char* value(const ::cv_pkg::AddTwointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cv_pkg::AddTwointsResponse> should match
// service_traits::MD5Sum< ::cv_pkg::AddTwoints >
template<>
struct MD5Sum< ::cv_pkg::AddTwointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cv_pkg::AddTwoints >::value();
  }
  static const char* value(const ::cv_pkg::AddTwointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cv_pkg::AddTwointsResponse> should match
// service_traits::DataType< ::cv_pkg::AddTwoints >
template<>
struct DataType< ::cv_pkg::AddTwointsResponse>
{
  static const char* value()
  {
    return DataType< ::cv_pkg::AddTwoints >::value();
  }
  static const char* value(const ::cv_pkg::AddTwointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CV_PKG_MESSAGE_ADDTWOINTS_H
