// Generated by gencpp from file cv_pkg/AddTwoInts.msg
// DO NOT EDIT!


#ifndef CV_PKG_MESSAGE_ADDTWOINTS_H
#define CV_PKG_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <cv_pkg/AddTwoIntsRequest.h>
#include <cv_pkg/AddTwoIntsResponse.h>


namespace cv_pkg
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace cv_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cv_pkg::AddTwoInts > {
  static const char* value()
  {
    return "4a399bc94c653d283002e008e813f40e";
  }

  static const char* value(const ::cv_pkg::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::cv_pkg::AddTwoInts > {
  static const char* value()
  {
    return "cv_pkg/AddTwoInts";
  }

  static const char* value(const ::cv_pkg::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::cv_pkg::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::cv_pkg::AddTwoInts >
template<>
struct MD5Sum< ::cv_pkg::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cv_pkg::AddTwoInts >::value();
  }
  static const char* value(const ::cv_pkg::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cv_pkg::AddTwoIntsRequest> should match
// service_traits::DataType< ::cv_pkg::AddTwoInts >
template<>
struct DataType< ::cv_pkg::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::cv_pkg::AddTwoInts >::value();
  }
  static const char* value(const ::cv_pkg::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cv_pkg::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::cv_pkg::AddTwoInts >
template<>
struct MD5Sum< ::cv_pkg::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cv_pkg::AddTwoInts >::value();
  }
  static const char* value(const ::cv_pkg::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cv_pkg::AddTwoIntsResponse> should match
// service_traits::DataType< ::cv_pkg::AddTwoInts >
template<>
struct DataType< ::cv_pkg::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::cv_pkg::AddTwoInts >::value();
  }
  static const char* value(const ::cv_pkg::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CV_PKG_MESSAGE_ADDTWOINTS_H
