// Generated by gencpp from file cv_pkg/fruit_classify.msg
// DO NOT EDIT!


#ifndef CV_PKG_MESSAGE_FRUIT_CLASSIFY_H
#define CV_PKG_MESSAGE_FRUIT_CLASSIFY_H

#include <ros/service_traits.h>


#include <cv_pkg/fruit_classifyRequest.h>
#include <cv_pkg/fruit_classifyResponse.h>


namespace cv_pkg
{

struct fruit_classify
{

typedef fruit_classifyRequest Request;
typedef fruit_classifyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct fruit_classify
} // namespace cv_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cv_pkg::fruit_classify > {
  static const char* value()
  {
    return "4a399bc94c653d283002e008e813f40e";
  }

  static const char* value(const ::cv_pkg::fruit_classify&) { return value(); }
};

template<>
struct DataType< ::cv_pkg::fruit_classify > {
  static const char* value()
  {
    return "cv_pkg/fruit_classify";
  }

  static const char* value(const ::cv_pkg::fruit_classify&) { return value(); }
};


// service_traits::MD5Sum< ::cv_pkg::fruit_classifyRequest> should match
// service_traits::MD5Sum< ::cv_pkg::fruit_classify >
template<>
struct MD5Sum< ::cv_pkg::fruit_classifyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cv_pkg::fruit_classify >::value();
  }
  static const char* value(const ::cv_pkg::fruit_classifyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cv_pkg::fruit_classifyRequest> should match
// service_traits::DataType< ::cv_pkg::fruit_classify >
template<>
struct DataType< ::cv_pkg::fruit_classifyRequest>
{
  static const char* value()
  {
    return DataType< ::cv_pkg::fruit_classify >::value();
  }
  static const char* value(const ::cv_pkg::fruit_classifyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cv_pkg::fruit_classifyResponse> should match
// service_traits::MD5Sum< ::cv_pkg::fruit_classify >
template<>
struct MD5Sum< ::cv_pkg::fruit_classifyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cv_pkg::fruit_classify >::value();
  }
  static const char* value(const ::cv_pkg::fruit_classifyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cv_pkg::fruit_classifyResponse> should match
// service_traits::DataType< ::cv_pkg::fruit_classify >
template<>
struct DataType< ::cv_pkg::fruit_classifyResponse>
{
  static const char* value()
  {
    return DataType< ::cv_pkg::fruit_classify >::value();
  }
  static const char* value(const ::cv_pkg::fruit_classifyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CV_PKG_MESSAGE_FRUIT_CLASSIFY_H
