// Generated by gencpp from file cv_pkg/ImageClassifyRequest.msg
// DO NOT EDIT!


#ifndef CV_PKG_MESSAGE_IMAGECLASSIFYREQUEST_H
#define CV_PKG_MESSAGE_IMAGECLASSIFYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cv_pkg
{
template <class ContainerAllocator>
struct ImageClassifyRequest_
{
  typedef ImageClassifyRequest_<ContainerAllocator> Type;

  ImageClassifyRequest_()
    : image_path()  {
    }
  ImageClassifyRequest_(const ContainerAllocator& _alloc)
    : image_path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _image_path_type;
  _image_path_type image_path;





  typedef boost::shared_ptr< ::cv_pkg::ImageClassifyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cv_pkg::ImageClassifyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ImageClassifyRequest_

typedef ::cv_pkg::ImageClassifyRequest_<std::allocator<void> > ImageClassifyRequest;

typedef boost::shared_ptr< ::cv_pkg::ImageClassifyRequest > ImageClassifyRequestPtr;
typedef boost::shared_ptr< ::cv_pkg::ImageClassifyRequest const> ImageClassifyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cv_pkg::ImageClassifyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cv_pkg::ImageClassifyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cv_pkg::ImageClassifyRequest_<ContainerAllocator1> & lhs, const ::cv_pkg::ImageClassifyRequest_<ContainerAllocator2> & rhs)
{
  return lhs.image_path == rhs.image_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cv_pkg::ImageClassifyRequest_<ContainerAllocator1> & lhs, const ::cv_pkg::ImageClassifyRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cv_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cv_pkg::ImageClassifyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cv_pkg::ImageClassifyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cv_pkg::ImageClassifyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cv_pkg::ImageClassifyRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cv_pkg::ImageClassifyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cv_pkg::ImageClassifyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cv_pkg::ImageClassifyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65568c775bfbc96c6265c3d13d7e1a07";
  }

  static const char* value(const ::cv_pkg::ImageClassifyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65568c775bfbc96cULL;
  static const uint64_t static_value2 = 0x6265c3d13d7e1a07ULL;
};

template<class ContainerAllocator>
struct DataType< ::cv_pkg::ImageClassifyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cv_pkg/ImageClassifyRequest";
  }

  static const char* value(const ::cv_pkg::ImageClassifyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cv_pkg::ImageClassifyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string image_path\n"
;
  }

  static const char* value(const ::cv_pkg::ImageClassifyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cv_pkg::ImageClassifyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.image_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageClassifyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cv_pkg::ImageClassifyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cv_pkg::ImageClassifyRequest_<ContainerAllocator>& v)
  {
    s << indent << "image_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.image_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CV_PKG_MESSAGE_IMAGECLASSIFYREQUEST_H
