// Generated by gencpp from file cv_pkg/ImageClassify.msg
// DO NOT EDIT!


#ifndef CV_PKG_MESSAGE_IMAGECLASSIFY_H
#define CV_PKG_MESSAGE_IMAGECLASSIFY_H

#include <ros/service_traits.h>


#include <cv_pkg/ImageClassifyRequest.h>
#include <cv_pkg/ImageClassifyResponse.h>


namespace cv_pkg
{

struct ImageClassify
{

typedef ImageClassifyRequest Request;
typedef ImageClassifyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImageClassify
} // namespace cv_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cv_pkg::ImageClassify > {
  static const char* value()
  {
    return "4a399bc94c653d283002e008e813f40e";
  }

  static const char* value(const ::cv_pkg::ImageClassify&) { return value(); }
};

template<>
struct DataType< ::cv_pkg::ImageClassify > {
  static const char* value()
  {
    return "cv_pkg/ImageClassify";
  }

  static const char* value(const ::cv_pkg::ImageClassify&) { return value(); }
};


// service_traits::MD5Sum< ::cv_pkg::ImageClassifyRequest> should match
// service_traits::MD5Sum< ::cv_pkg::ImageClassify >
template<>
struct MD5Sum< ::cv_pkg::ImageClassifyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cv_pkg::ImageClassify >::value();
  }
  static const char* value(const ::cv_pkg::ImageClassifyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cv_pkg::ImageClassifyRequest> should match
// service_traits::DataType< ::cv_pkg::ImageClassify >
template<>
struct DataType< ::cv_pkg::ImageClassifyRequest>
{
  static const char* value()
  {
    return DataType< ::cv_pkg::ImageClassify >::value();
  }
  static const char* value(const ::cv_pkg::ImageClassifyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cv_pkg::ImageClassifyResponse> should match
// service_traits::MD5Sum< ::cv_pkg::ImageClassify >
template<>
struct MD5Sum< ::cv_pkg::ImageClassifyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cv_pkg::ImageClassify >::value();
  }
  static const char* value(const ::cv_pkg::ImageClassifyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cv_pkg::ImageClassifyResponse> should match
// service_traits::DataType< ::cv_pkg::ImageClassify >
template<>
struct DataType< ::cv_pkg::ImageClassifyResponse>
{
  static const char* value()
  {
    return DataType< ::cv_pkg::ImageClassify >::value();
  }
  static const char* value(const ::cv_pkg::ImageClassifyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CV_PKG_MESSAGE_IMAGECLASSIFY_H
